### PR TITLE
Switch to stable version of spatie/laravel-package-tools

### PR DESCRIPTION
**Pull request by nickknissen**
The branch `master` is renamed to `main` and a stable version preferred to avoid breaking changes.

### CODE REVIEW

**Comment by beblife** [comment]
@nickknissen Thanks for this, didn't realise this was using `dev-master`!

**Comment by beblife** [comment]
Looks like the CI is failing, I'll have a look later today to fix this so this can get merged.

**Comment by nickknissen** [comment]
@beblife The problems seems to be openapi-psr7-validator/php-openapi which had some type erros. 
It should be fixed with my latest commit which bumbs openapi-psr7-validator to 0.17

**Comment by beblife** [comment]
@nickknissen That did fix it, thanks!

**Pull request merged**
